#ifndef _CognitiveBiases_
#define _CognitiveBiases_
const char* const cognitiveBiasesList[] = {
  "Actor-observer bias\n\nThe tendency for explanations of other individuals' behaviors to overemphasize the influence of their personality and underemphasize the influence of their situation (see also Fundamental attribution error), and for explanations of one's own behaviors to do the opposite (that is, to overemphasize the influence of our situation and underemphasize the influence of our own personality).",
  "Agent detection\n\nThe inclination to presume the purposeful intervention of a sentient or intelligent agent.",
  "Ambiguity effect\n\nThe tendency to avoid options for which the probability of a favorable outcome is unknown.",
  "Anchoring or focalism\n\nThe tendency to rely too heavily, or \"anchor\", on one trait or piece of information when making decisions (usually the first piece of information acquired on that subject).",
  "Anthropocentric thinking\n\nThe tendency to use human analogies as a basis for reasoning about other, less familiar, biological phenomena.",
  "Anthropomorphism or personification\n\nThe tendency to characterize animals, objects, and abstract concepts as possessing human-like traits, emotions, and intentions. The opposite bias, of not attributing feelings or thoughts to another person, is dehumanised perception, a type of objectification.",
  "Attentional bias\n\nThe tendency of perception to be affected by recurring thoughts.",
  "Attribute substitution\n\nOccurs when a judgment has to be made (of a target attribute) that is computationally complex, and instead a more easily calculated heuristic attribute is substituted. This substitution is thought of as taking place in the automatic intuitive judgment system, rather than the more self-aware reflective system.",
  "Authority bias\n\nThe tendency to attribute greater accuracy to the opinion of an authority figure (unrelated to its content) and be more influenced by that opinion.",
  "Automation bias\n\nThe tendency to depend excessively on automated systems which can lead to erroneous automated information overriding correct decisions.",
  "Availability cascade\n\nA self-reinforcing process in which a collective belief gains more and more plausibility through its increasing repetition in public discourse (or \"repeat something long enough and it will become true\").",
  "Availability heuristic\n\nThe tendency to overestimate the likelihood of events with greater \"availability\" in memory, which can be influenced by how recent the memories are or how unusual or emotionally charged they may be.",
  "Backfire effect\n\nThe reaction to disconfirming evidence by strengthening one's previous beliefs. Note: the existence of this bias as a widespread phenomenon has been disputed in empirical studies",
  "Bandwagon effect\n\nThe tendency to do (or believe) things because many other people do (or believe) the same. Related to groupthink and herd behavior.",
  "Base rate fallacy or Base rate neglect\n\nThe tendency to ignore general information and focus on information only pertaining to the specific case, even when the general information is more important.",
  "Belief bias\n\nAn effect where someone's evaluation of the logical strength of an argument is biased by the believability of the conclusion.",
  "Ben Franklin effect\n\nA person who has performed a favor for someone is more likely to do another favor for that person than they would be if they had received a favor from that person.",
  "Berkson's paradox\n\nThe tendency to misinterpret statistical experiments involving conditional probabilities.",
  "Bias blind spot\n\nThe tendency to see oneself as less biased than other people, or to be able to identify more cognitive biases in others than in oneself.",
  "Cheerleader effect\n\nThe tendency for people to appear more attractive in a group than in isolation.",
  "Clustering illusion\n\nThe tendency to overestimate the importance of small runs, streaks, or clusters in large samples of random data (that is, seeing phantom patterns).",
  "Compassion fade\n\nThe predisposition to behave more compassionately towards a small number of identifiable victims than to a large number of anonymous ones.",
  "Confirmation bias\n\nThe tendency to search for, interpret, focus on and remember information in a way that confirms one's preconceptions.",
  "Congruence bias\n\nThe tendency to test hypotheses exclusively through direct testing, instead of testing possible alternative hypotheses.",
  "Conjunction fallacy\n\nThe tendency to assume that specific conditions are more probable than a more general version of those same conditions. For example, subjects in one experiment perceived the probability of a woman being both a bank teller and a feminist as more likely than the probability of her being a bank teller.",
  "Conservatism bias (belief revision)\n\nThe tendency to revise one's belief insufficiently when presented with new evidence.",
  "Continued influence effect\n\nThe tendency to believe previously learned misinformation even after it has been corrected. Misinformation can still influence inferences one generates after a correction has occurred. cf. Backfire effect",
  "Contrast effect\n\nThe enhancement or reduction of a certain stimulus' perception when compared with a recently observed, contrasting object.",
  "Courtesy bias\n\nThe tendency to give an opinion that is more socially correct than one's true opinion, so as to avoid offending anyone.",
  "Curse of knowledge\n\nWhen better-informed people find it extremely difficult to think about problems from the perspective of lesser-informed people.",
  "Declinism\n\nThe predisposition to view the past favorably (rosy retrospection) and future negatively.",
  "Decoy effect\n\nPreferences for either option A or B change in favor of option B when option C is presented, which is completely dominated by option B (inferior in all respects) and partially dominated by option A.",
  "Default effect\n\nWhen given a choice between several options, the tendency to favor the default one.",
  "Defensive attribution hypothesis\n\nAttributing more blame to a harm-doer as the outcome becomes more severe or as personal or situational similarity to the victim increases.",
  "Denomination effect\n\nThe tendency to spend more money when it is denominated in small amounts (e.g., coins) rather than large amounts (e.g., bills).",
  "Disposition effect\n\nThe tendency to sell an asset that has accumulated in value and resist selling an asset that has declined in value.",
  "Distinction bias\n\nThe tendency to view two options as more dissimilar when evaluating them simultaneously than when evaluating them separately.",
  "Dread aversion\n\nJust as losses yield double the emotional impact of gains, dread yields double the emotional impact of savouring.",
  "Dunning-Kruger effect\n\nThe tendency for unskilled individuals to overestimate their own ability and the tendency for experts to underestimate their own ability.",
  "Duration neglect\n\nThe neglect of the duration of an episode in determining its value.",
  "Egocentric bias\n\nOccurs when people claim more responsibility for themselves for the results of a joint action than an outside observer would credit them with.",
  "Empathy gap\n\nThe tendency to underestimate the influence or strength of feelings, in either oneself or others.",
  "End-of-history illusion\n\nThe age-independent belief that one will change less in the future than one has in the past.",
  "Endowment effect\n\nThe tendency for people to demand much more to give up an object than they would be willing to pay to acquire it.",
  "Exaggerated expectation\n\nThe tendency to expect or predict more extreme outcomes than those outcomes that actually happen.",
  "Experimenter's or expectation bias\n\nThe tendency for experimenters to believe, certify, and publish data that agree with their expectations for the outcome of an experiment, and to disbelieve, discard, or downgrade the corresponding weightings for data that appear to conflict with those expectations.",
  "Extrinsic incentives bias\n\nAn exception to the fundamental attribution error, when people view others as having (situational) extrinsic motivations and (dispositional) intrinsic motivations for oneself",
  "False consensus effect\n\nThe tendency for people to overestimate the degree to which others agree with them.",
  "False uniqueness bias\n\nThe tendency of people to see their projects and themselves as more singular than they actually are.",
  "Forer effect or Barnum effect\n\nThe observation that individuals will give high accuracy ratings to descriptions of their personality that supposedly are tailored specifically for them, but are in fact vague and general enough to apply to a wide range of people. This effect can provide a partial explanation for the widespread acceptance of some beliefs and practices, such as astrology, fortune telling, graphology, and some types of personality tests.",
  "Form function attribution bias\n\nIn human-robot interaction, the tendency of people to make systematic errors when interacting with a robot. People may base their expectations and perceptions of a robot on its appearance (form) and attribute functions which do not necessarily mirror the true functions of the robot.",
  "Framing effect\n\nDrawing different conclusions from the same information, depending on how that information is presented.",
  "Frequency illusion or Baader-Meinhof phenomenon\n\nThe frequency illusion is that once something has been noticed then every instance of that thing is noticed, leading to the belief it has a high frequency of occurrence (a form of selection bias). The Baader-Meinhof phenomenon is the illusion where something that has recently come to one's attention suddenly seems to appear with improbable frequency shortly afterwards. It was named after an incidence of frequency illusion in which the Baader-Meinhof Group was mentioned.",
  "Functional fixedness\n\nLimits a person to using an object only in the way it is traditionally used.",
  "Fundamental attribution error\n\nThe tendency for people to over-emphasize personality-based explanations for behaviors observed in others while under-emphasizing the role and power of situational influences on the same behavior (see also actor-observer bias, group attribution error, positivity effect, and negativity effect).",
  "Gambler's fallacy\n\nThe tendency to think that future probabilities are altered by past events, when in reality they are unchanged. The fallacy arises from an erroneous conceptualization of the law of large numbers. For example, \"I've flipped heads with this coin five times consecutively, so the chance of tails coming out on the sixth flip is much greater than heads.\"",
  "Gender bias\n\nA widely held set of implicit biases that discriminate against a gender. For example, the assumption that women are less suited to jobs requiring high intellectual ability. Or the assumption that people or animals are male in the absence of any indicators of gender.",
  "Group attribution error\n\nThe biased belief that the characteristics of an individual group member are reflective of the group as a whole or the tendency to assume that group decision outcomes reflect the preferences of group members, even when information is available that clearly suggests otherwise.",
  "Groupthink\n\nThe psychological phenomenon that occurs within a group of people in which the desire for harmony or conformity in the group results in an irrational or dysfunctional decision-making outcome. Group members try to minimize conflict and reach a consensus decision without critical evaluation of alternative viewpoints by actively suppressing dissenting viewpoints, and by isolating themselves from outside influences.",
  "Halo effect\n\nThe tendency for a person's positive or negative traits to \"spill over\" from one personality area to another in others' perceptions of them (see also physical attractiveness stereotype).",
  "Hard-easy effect\n\nThe tendency to overestimate one's ability to accomplish hard tasks, and underestimate one's ability to accomplish easy tasks",
  "Hindsight bias\n\nSometimes called the \"I-knew-it-all-along\" effect, the tendency to see past events as being predictable at the time those events happened.",
  "Hostile attribution bias\n\nThe \"hostile attribution bias\" is the tendency to interpret others' behaviors as having hostile intent, even when the behavior is ambiguous or benign.",
  "Hot-hand fallacy\n\nThe \"hot-hand fallacy\" (also known as the \"hot hand phenomenon\" or \"hot hand\") is the belief that a person who has experienced success with a random event has a greater chance of further success in additional attempts.",
  "Hyperbolic discounting\n\nDiscounting is the tendency for people to have a stronger preference for more immediate payoffs relative to later payoffs. Hyperbolic discounting leads to choices that are inconsistent over time - people make choices today that their future selves would prefer not to have made, despite using the same reasoning. Also known as current moment bias, present-bias, and related to Dynamic inconsistency. A good example of this: a study showed that when making food choices for the coming week, 74% of participants chose fruit, whereas when the food choice was for the current day, 70% chose chocolate.",
  "IKEA effect\n\nThe tendency for people to place a disproportionately high value on objects that they partially assembled themselves, such as furniture from IKEA, regardless of the quality of the end product.",
  "Illicit transference\n\nOccurs when a term in the distributive (referring to every member of a class) and collective (referring to the class itself as a whole) sense are treated as equivalent. The two variants of this fallacy are the fallacy of composition and the fallacy of division.",
  "Illusion of asymmetric insight\n\nPeople perceive their knowledge of their peers to surpass their peers' knowledge of them.",
  "Illusion of control\n\nThe tendency to overestimate one's degree of influence over other external events.",
  "Illusion of transparency\n\nThe tendency for people to overestimate the degree to which their personal mental state is known by others, and to overestimate how well they understand others' personal mental states.",
  "Illusion of validity\n\nOverestimating the accurracy of one's judgments, especially when available information is consistent or inter-correlated.",
  "Illusory correlation\n\nInaccurately perceiving a relationship between two unrelated events.",
  "Illusory superiority\n\nOverestimating one's desirable qualities, and underestimating undesirable qualities, relative to other people. (Also known as \"Lake Wobegon effect\", \"better-than-average effect\", or \"superiority bias\".)",
  "Illusory truth effect\n\nA tendency to believe that a statement is true if it is easier to process, or if it has been stated multiple times, regardless of its actual veracity. These are specific cases of truthiness.",
  "Impact bias\n\nThe tendency to overestimate the length or the intensity of the impact of future feeling states.",
  "Implicit association\n\nThe speed with which people can match words depends on how closely they are associated.",
  "Information bias\n\nThe tendency to seek information even when it cannot affect action.",
  "Ingroup bias\n\nThe tendency for people to give preferential treatment to others they perceive to be members of their own groups.",
  "Insensitivity to sample size\n\nThe tendency to under-expect variation in small samples.",
  "Intentionality bias\n\nTendency to judge human action to be intentional rather than accidental.",
  "Interoceptive bias\n\nThe tendency for sensory input about the body itself to affect one's judgement about external, unrelated circumstances. (As for example, in parole judges who are more lenient when fed and rested.)",
  "Irrational escalation or Escalation of commitment\n\nThe phenomenon where people justify increased investment in a decision, based on the cumulative prior investment, despite new evidence suggesting that the decision was probably wrong. Also known as the sunk cost fallacy.",
  "Just-world hypothesis\n\nThe tendency for people to want to believe that the world is fundamentally just, causing them to rationalize an otherwise inexplicable injustice as deserved by the victim(s).",
  "Law of the instrument\n\nAn over-reliance on a familiar tool or methods, ignoring or under-valuing alternative approaches. \"If all you have is a hammer, everything looks like a nail.\"",
  "Less-is-better effect\n\nThe tendency to prefer a smaller set to a larger set judged separately, but not jointly.",
  "Loss aversion\n\nThe perceived disutility of giving up an object is greater than the utility associated with acquiring it. (see also Sunk cost effects and endowment effect).",
  "Mere exposure effect\n\nThe tendency to express undue liking for things merely because of familiarity with them.",
  "Money illusion\n\nThe tendency to concentrate on the nominal value (face value) of money rather than its value in terms of purchasing power.",
  "Moral credential effect\n\nOccurs when someone who does something good gives themselves permission to be less good in the future.",
  "Moral luck\n\nThe tendency for people to ascribe greater or lesser moral standing based on the outcome of an event.",
  "Naïve cynicism\n\nExpecting more egocentric bias in others than in oneself.",
  "Naïve realism\n\nThe belief that we see reality as it really is - objectively and without bias; that the facts are plain for all to see; that rational people will agree with us; and that those who don't are either uninformed, lazy, irrational, or biased.",
  "Neglect of probability\n\nThe tendency to completely disregard probability when making a decision under uncertainty.",
  "Non-adaptive choice switching\n\nAfter experiencing a bad outcome with a decision problem, the tendency to avoid the choice previously made when faced with the same decision problem again, even though the choice was optimal. Also known as \"once bitten, twice shy\" or \"hot stove effect\".",
  "Normalcy bias\n\nThe refusal to plan for, or react to, a disaster which has never happened before.",
  "Not invented here\n\nAversion to contact with or use of products, research, standards, or knowledge developed outside a group. Related to IKEA effect.",
  "Observer-expectancy effect\n\nWhen a researcher expects a given result and therefore unconsciously manipulates an experiment or misinterprets data in order to find it (see also subject-expectancy effect).",
  "Omission bias\n\nThe tendency to judge harmful actions (commissions) as worse, or less moral, than equally harmful inactions (omissions).",
  "Optimism bias\n\nThe tendency to be over-optimistic, underestimating greatly the probability of undesirable outcomes and overestimating favorable and pleasing outcomes (see also wishful thinking, valence effect, positive outcome bias).",
  "Ostrich effect\n\nIgnoring an obvious (negative) situation.",
  "Outcome bias\n\nThe tendency to judge a decision by its eventual outcome instead of based on the quality of the decision at the time it was made.",
  "Outgroup homogeneity bias\n\nIndividuals see members of their own group as being relatively more varied than members of other groups.",
  "Overconfidence effect\n\nExcessive confidence in one's own answers to questions. For example, for certain types of questions, answers that people rate as \"99% certain\" turn out to be wrong 40% of the time.",
  "Pareidolia\n\nA vague and random stimulus (often an image or sound) is perceived as significant, e.g., seeing images of animals or faces in clouds, the man in the moon, and hearing non-existent hidden messages on records played in reverse.",
  "Parkinson's law of triviality\n\nThe tendency to give disproportionate weight to trivial issues. Also known as bikeshedding, this bias explains why an organization may avoid specialized or complex subjects, such as the design of a nuclear reactor, and instead focus on something easy to grasp or rewarding to the average participant, such as the design of an adjacent bike shed.",
  "Pessimism bias\n\nThe tendency for some people, especially those suffering from depression, to overestimate the likelihood of negative things happening to them.",
  "Plan continuation bias\n\nFailure to recognize that the original plan of action is no longer appropriate for a changing situation or for a situation that is different than anticipated.",
  "Planning fallacy\n\nThe tendency to underestimate one's own task-completion times.",
  "Plant blindness\n\nThe tendency to ignore plants in their environment and a failure to recognize and appreciate the utility of plants to life on earth.",
  "Present bias\n\nThe tendency of people to give stronger weight to payoffs that are closer to the present time when considering trade-offs between two future moments.",
  "Pro-innovation bias\n\nThe tendency to have an excessive optimism towards an invention or innovation's usefulness throughout society, while often failing to identify its limitations and weaknesses.",
  "Probability matching\n\nSub-optimal matching of the probability of choices with the probability of reward in a stochastic context.",
  "Projection bias\n\nThe tendency to overestimate how much our future selves share one's current preferences, thoughts and values, thus leading to sub-optimal choices.",
  "Proportionality bias\n\nOur innate tendency to assume that big events have big causes, may also explain our tendency to accept conspiracy theories.",
  "Pseudocertainty effect\n\nThe tendency to make risk-averse choices if the expected outcome is positive, but make risk-seeking choices to avoid negative outcomes.",
  "Puritanical bias\n\nRefers to the tendency to attribute cause of an undesirable outcome or wrongdoing by an individual to a moral deficiency or lack of self-control rather than taking into account the impact of broader societal determinants .",
  "Pygmalion effect\n\nThe phenomenon whereby others' expectations of a target person affect the target person's performance.",
  "Reactance\n\nThe urge to do the opposite of what someone wants you to do out of a need to resist a perceived attempt to constrain your freedom of choice (see also Reverse psychology).",
  "Reactive devaluation\n\nDevaluing proposals only because they purportedly originated with an adversary.",
  "Recency illusion\n\nThe illusion that a phenomenon one has noticed only recently is itself recent. Often used to refer to linguistic phenomena; the illusion that a word or language usage that one has noticed only recently is an innovation when it is, in fact, long-established (see also frequency illusion).",
  "Restraint bias\n\nThe tendency to overestimate one's ability to show restraint in the face of temptation.",
  "Rhyme as reason effect\n\nRhyming statements are perceived as more truthful.",
  "Risk compensation / Peltzman effect\n\nThe tendency to take greater risks when perceived safety increases.",
  "Salience bias\n\nThe tendency to focus on items that are more prominent or emotionally striking and ignore those that are unremarkable, even though this difference is often irrelevant by objective standards.",
  "Scope neglect or scope insensitivity\n\nThe tendency to be insensitive to the size of a problem when evaluating it. For example, being willing to pay as much to save 2,000 children or 20,000 children",
  "Selection bias\n\nThe tendency to notice something more when something causes us to be more aware of it, such as when we buy a car, we tend to notice similar cars more often than we did before. They are not suddenly more common - we just are noticing them more. Also called the Observational Selection Bias.",
  "Selective perception\n\nThe tendency for expectations to affect perception.",
  "Self-serving bias\n\nThe tendency to claim more responsibility for successes than failures. It may also manifest itself as a tendency for people to evaluate ambiguous information in a way beneficial to their interests (see also group-serving bias).",
  "Semmelweis reflex\n\nThe tendency to reject new evidence that contradicts a paradigm.",
  "Sexual overperception bias / Sexual underperception bias\n\nThe tendency to over-/underestimate sexual interest of another person in oneself.",
  "Shared information bias\n\nKnown as the tendency for group members to spend more time and energy discussing information that all members are already familiar with (i.e., shared information), and less time and energy discussing information that only some members are aware of (i.e., unshared information).",
  "Social comparison bias\n\nThe tendency, when making decisions, to favour potential candidates who don't compete with one's own particular strengths.",
  "Social desirability bias\n\nThe tendency to over-report socially desirable characteristics or behaviours in oneself and under-report socially undesirable characteristics or behaviours. See also: § Courtesy bias.",
  "Status quo bias\n\nThe tendency to like things to stay relatively the same (see also loss aversion, endowment effect, and system justification).",
  "Stereotyping\n\nExpecting a member of a group to have certain characteristics without having actual information about that individual.",
  "Subadditivity effect\n\nThe tendency to judge the probability of the whole to be less than the probabilities of the parts.",
  "Subjective validation\n\nPerception that something is true if a subject's belief demands it to be true. Also assigns perceived connections between coincidences.",
  "Surrogation\n\nLosing sight of the strategic construct that a measure is intended to represent, and subsequently acting as though the measure is the construct of interest.",
  "Survivorship bias\n\nConcentrating on the people or things that \"survived\" some process and inadvertently overlooking those that didn't because of their lack of visibility.",
  "System justification\n\nThe tendency to defend and bolster the status quo. Existing social, economic, and political arrangements tend to be preferred, and alternatives disparaged, sometimes even at the expense of individual and collective self-interest. (See also status quo bias.)",
  "Systematic bias\n\nJudgement that arises when targets of differentiating judgement become subject to effects of regression that are not equivalent.",
  "Third-person effect\n\nA hypothesized tendency to believe that mass communicated media messages have a greater effect on others than on themselves. As of 2020, the third-person effect has yet to be reliably demonstrated in a scientific context.",
  "Time-saving bias\n\nUnderestimations of the time that could be saved (or lost) when increasing (or decreasing) from a relatively low speed and overestimations of the time that could be saved (or lost) when increasing (or decreasing) from a relatively high speed.",
  "Trait ascription bias\n\nThe tendency for people to view themselves as relatively variable in terms of personality, behavior, and mood while viewing others as much more predictable.",
  "Ultimate attribution error\n\nSimilar to the fundamental attribution error, in this error a person is likely to make an internal attribution to an entire group instead of the individuals within the group.",
  "Unconscious bias\n\nAlso known as implicit biases, are the underlying attitudes and stereotypes that people unconsciously attribute to another person or group of people that affect how they understand and engage with them. Many researchers suggest that unconscious bias occurs automatically as the brain makes quick judgments based on past experiences and background.",
  "Unit bias\n\nThe standard suggested amount of consumption (e.g., food serving size) is perceived to be appropriate, and a person would consume it all even if it is too much for this particular person.",
  "Weber-Fechner law\n\nDifficulty in comparing small differences in large quantities.",
  "Well travelled road effect\n\nUnderestimation of the duration taken to traverse oft-travelled routes and overestimation of the duration taken to traverse less familiar routes.",
  "Women are wonderful effect\n\nA tendency to associate more positive attributes with women than with men.",
  "Worse-than-average effect\n\nA tendency to believe ourselves to be worse than others at tasks which are difficult.",
  "Zero-risk bias\n\nPreference for reducing a small risk to zero over a greater reduction in a larger risk.",
  "Zero-sum bias\n\nA bias whereby a situation is incorrectly perceived to be like a zero-sum game (i.e., one person gains at the expense of another).",
  nullptr
};

#endif
